### ISSUE TITLE
Suggestions for the installation readme/wiki

### ISSUE THREAD

**Issue by simoninns** [rhys101/beebem#21]
Add the git clone command to the current instructions; since it's on a branch it might not be obvious:
git clone -b rel-0.0.13-domesday https://github.com/rhys101/beebem.git 

BeebEm requires autoconf and python installed before building:
sudo apt install autoconf python

**Comment by rhys101** [comment]
Thanks Simon - I've updated the README on the branch with the clone instructions and the autoconf / python dependencies for linux.
